FROM nvidia/cuda:12.1-cudnn8-runtime-python3.12

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY asr/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY asr/ .

EXPOSE 50051
CMD ["python", "server.py"]
